name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka zstandard customtkinter selenium requests pandas matplotlib pynput

      - name: Build EXE with Nuitka
        run: |
          python -m nuitka --standalone --onefile --windows-console-mode=disable --enable-plugin=tk-inter --include-data-files=chromedriver.exe=chromedriver.exe main.py
          # Мы изменили chromedriver.exe=. на chromedriver.exe=chromedriver.exe
          # И заменили старый флаг консоли на новый --windows-console-mode=disable

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDE_Filler_Windows
          path: main.exe
