name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka zstandard customtkinter selenium requests pandas matplotlib pynput
          # Мы используем python -m pip для надежности и добавили zstandard

      - name: Build EXE with Nuitka
        run: |
          python -m nuitka --standalone --onefile --windows-disable-console --enable-plugin=tk-inter --include-data-files=chromedriver.exe=. main.py
          # Исправили Nuitka на nuitka (с маленькой буквы)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HDE_Filler_Windows
          path: main.exe
